name: flutter_maestro_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  go_router: ^12.1.1
  riverpod_annotation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.7
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/
